# Generated by Django 4.2.8 on 2025-02-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_event_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
