# Generated by Django 4.2.8 on 2025-02-08 21:12

from django.db import migrations, models
import myapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_event_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='image',
        ),
        migrations.AddField(
            model_name='eventimage',
            name='image_url',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=myapp.storage.EventMediaStorage(), upload_to=''),
        ),
    ]
