# Generated by Django 4.2.8 on 2025-02-08 21:34

from django.db import migrations, models
import myapp.storage


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_eventimage_image_eventimage_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(default='null', storage=myapp.storage.EventGalleryStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
