# Generated by Django 4.2.8 on 2025-03-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_sportsstable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsstable',
            name='notes',
        ),
        migrations.AddField(
            model_name='sportsstable',
            name='agree_to_waiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sportsstable',
            name='dob',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsstable',
            name='electronic_signature',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsstable',
            name='emergency_contact_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsstable',
            name='emergency_contact_phone',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
