# Generated by Django 4.2.8 on 2025-04-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_attendancepayment_playerprofile_delete_sportsstable'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
