# Generated by Django 4.2.8 on 2025-07-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_playerprofile_marketing_opt_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUnsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(blank=True, choices=[('too_many', 'I receive too many emails'), ('not_relevant', 'Content is not relevant to me'), ('never_signed_up', 'I never signed up for these emails'), ('other', 'Other reason')], max_length=50, null=True)),
                ('other_reason', models.TextField(blank=True, null=True)),
                ('date_unsubscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
