# Generated by Django 4.2.8 on 2025-09-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_emailunsubscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='age_category',
            field=models.CharField(choices=[('adult', 'Adult (18+)'), ('minor', 'Minor (Under 18)')], default='adult', max_length=10),
        ),
    ]
