# Generated by Django 4.2.8 on 2025-09-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_playerprofile_age_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
