# Generated by Django 4.2.8 on 2026-03-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_oneoffevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneoffevent',
            name='ticket_type',
            field=models.CharField(choices=[('player', 'Player Ticket'), ('player_plus', 'Player + Brunch Ticket'), ('spectator', 'Spectator (Free)')], default='player', max_length=20),
        ),
    ]
